#
# Copyright (C) 2020 vietanhbui2000 (vietanhbui2000@gmail.com)
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Material Theme
LUCI_DEPENDS:=
LUCI_PKGARCH:=all
PKG_VERSION:=2020.04.20
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
