#!/bin/sh /etc/rc.common

START=99
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
	logger -t ttyd 'Starting ttyd service'
	service_start /usr/bin/ttyd -i br-lan /bin/login
	return 0
}

stop() {
	if [ -n "`pidof ttyd`" ]; then
		logger -t ttyd 'Shutting down ttyd service'
		service_stop /usr/bin/ttyd
	fi
	return 0
}

restart() {
	logger -t ttyd 'Restarting ttyd service'
	stop
	sleep 2
	start
}
